language: node_js
node_js:
- "0.8"
- "0.10"
- "0.11"
- "0.12"
- "iojs"
- "4"
- "5"
- "6"
- "7"
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX="g++-4.8"
before_install:
- if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm; fi
